Description: >
    AWS 3 Tier Web Application -- database tier Non-IAM stack 2021 Feb

Parameters:
  S3DeploymentBucket:
    Description: AWS S3 Deployment bucket to hold deployment files
    Type: String
  S3BucketPrefix:
    Description: AWS S3 bucket prefix
    Type: String
  EnvironmentName:
    Description: An environment name that will be prefixed
    Type: String

Resources:
  DatabaseDynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub "https://${S3DeploymentBucket}.s3.us-west-2.amazonaws.com/${S3BucketPrefix}/cloudformation/template/AWS_Templates_DynamoDB.yml"
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        TableDescriptor: 'webapp'
        HashKeyElementName: 'UserID'
        HashKeyElementType: S
      Tags:
        - Key: Name
          Value: DatabaseDynamoDB
        - Key: SERVICE_CREATOR
          Value: eliu
        - Key: SERVICE_CATEGORY
          Value: APP
  
Outputs:
  DynamoDBTableName:
    Description: DynamoDB Table name
    Value: !GetAtt DatabaseDynamoDB.Outputs.TableName
