Description: >
    AWS 3 Tier Web Application -- database tier 2021 Feb

Parameters:
  S3DeploymentBucket:
    Description: AWS S3 Deployment bucket to hold deployment files
    Type: String
  S3BucketPrefix:
    Description: AWS S3 bucket prefix
    Type: String
  EnvironmentName:
    Description: An environment name that will be prefixed
    Type: String
  InfraEnvName:
    Description: AWS Infrastructure Env name
    Type: String
  EC2InstanceProfile:
    Description: EC2 Instace Profile name
    Type: String

Resources:
  WebTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 9
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId:
        Fn::ImportValue:
          !Sub "${InfraEnvName}-VPCID"
      Tags:
        - Key: SERVICE_CREATOR
          Value: eliu
        - Key: SERVICE_CATEGORY
          Value: APP

Outputs:
  WebAutoScalingGroup:
    Description: Web Tier Auto Scaling Group
    Value: !Ref WebAutoScalingGroup
  WebLBName:
    Description: Web Tier Load Balancer Name
    Value: !GetAtt WebLB.LoadBalancerName
  WebLBDnsName:
    Description: Web Tier Load Balancer DNS Value
    Value: !GetAtt WebLB.DNSName
