Description: >
    Eva Liu / AWS 3 Tier Web Application -- app tier 2021 May

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed
    Type: String
  S3DeploymentBucket:
    Description: AWS S3 Deployment bucket to hold deployment files
    Type: String
  S3BucketPrefix:
    Description: AWS S3 bucket prefix
    Type: String
  DynamoDBTableName:
    Description: DynamoDB table name for database access
    Type: String
  SQSInvokeArn:
    Description: Source SQS Arn that triggers Lambda function
    Type: String

Resources:
  AppTierIAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub "https://${S3DeploymentBucket}.s3.us-west-2.amazonaws.com/${S3BucketPrefix}/cloudformation/app_tier/iam.yml"
      Parameters:
        S3DeploymentBucket: !Ref S3DeploymentBucket
        S3BucketPrefix: !Ref S3BucketPrefix
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Name
          Value: AppTierIAMStack
        - Key: SERVICE_CREATOR
          Value: eliu
        - Key: SERVICE_CATEGORY
          Value: APP

  AppTierNonIAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub "https://${S3DeploymentBucket}.s3.us-west-2.amazonaws.com/${S3BucketPrefix}/cloudformation/app_tier/non_iam.yml"
      Parameters:
        S3DeploymentBucket: !Ref S3DeploymentBucket
        S3BucketPrefix: !Ref S3BucketPrefix
        SQSInvokeArn: !Ref SQSInvokeArn
        EnvironmentName: !Ref EnvironmentName
        LambdaExecutionRole: !GetAtt AppTierIAM.Outputs.LambdaRoleName
        DynamoDBTableName: !Ref DynamoDBTableName
      Tags:
        - Key: Name
          Value: AppTierNonIAMStack
        - Key: SERVICE_CREATOR
          Value: eliu
        - Key: SERVICE_CATEGORY
          Value: APP

Outputs:
  LambdaIAMRole:
    Description: Web Tier EC2 Role
    Value: !GetAtt AppTierIAM.Outputs.LambdaRoleName
  LambdaFunctionName:
    Description: Web Tier ELB Name
    Value: !GetAtt AppTierNonIAMStack.Outputs.LambdaFunctionName
