Description: >
    AWS 3 Tier Web Application -- App tier Non-IAM stack, 2021 May

Parameters:
  S3DeploymentBucket:
    Description: AWS S3 Deployment bucket to hold deployment files
    Type: String
  S3BucketPrefix:
    Description: AWS S3 bucket prefix
    Type: String
  EnvironmentName:
    Description: An environment name that will be prefixed
    Type: String
  DynamoDBTableName:
    Description: DynamoDB table name for database access
    Type: String
  LambdaExecutionRole:
    Description: Lambda Execution Role name
    Type: String
  SQSInvokeArn:
    Description: Source SQS Arn that triggers Lambda function
    Type: String

Resources:
  AppTierLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub "https://${S3DeploymentBucket}.s3.us-west-2.amazonaws.com/${S3BucketPrefix}/cloudformation/template/AWS_Templates_Lambda.yml"
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        EnvironmentVariables: !Sub "TABLENAME=${DynamoDBTableName};NONE;NONE;NONE"
        LambdaDescriptor: 'webapplambda'
        S3Bucket: !Ref S3DeploymentBucket
        S3PrefixKey: !Sub "${S3BucketPrefix}/source/lambda/code_package.zip"
        Role: !Ref LambdaExecutionRole
        Handler: webapi.lambda_handler
        SQSInvokeArn: !Ref SQSInvokeArn
      Tags:
        - Key: SERVICE_CREATOR
          Value: eliu
        - Key: SERVICE_CATEGORY
          Value: APP

Outputs:
  LambdaFunctionName:
    Description: Web Tier Auto Scaling Group
    Value: !GetAtt AppTierLambda.Outputs.LambdaName
